select * from customer limit 20

--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

ALTER TABLE customer RENAME COLUMN "Customer ID" TO customer_id;
ALTER TABLE customer RENAME COLUMN "Age" TO age;
ALTER TABLE customer RENAME COLUMN "Gender" TO gender;
ALTER TABLE customer RENAME COLUMN "Item Purchased" TO item_purchased;
ALTER TABLE customer RENAME COLUMN "Category" TO category;
ALTER TABLE customer RENAME COLUMN "Purchase Amount (USD)" TO purchase_amount;
ALTER TABLE customer RENAME COLUMN "Location" TO location;
ALTER TABLE customer RENAME COLUMN "Size" TO size;
ALTER TABLE customer RENAME COLUMN "Color" TO color;
ALTER TABLE customer RENAME COLUMN "Season" TO season;
ALTER TABLE customer RENAME COLUMN "Review Rating" TO review_rating;
ALTER TABLE customer RENAME COLUMN "Subscription Status" TO subscription_status;
ALTER TABLE customer RENAME COLUMN "Shipping Type" TO shipping_type;
ALTER TABLE customer RENAME COLUMN "Discount Applied" TO discount_applied;
ALTER TABLE customer RENAME COLUMN "Promo Code Used" TO promo_code_used;
ALTER TABLE customer RENAME COLUMN "Previous Purchases" TO previous_purchases;
ALTER TABLE customer RENAME COLUMN "Payment Method" TO payment_method;
ALTER TABLE customer RENAME COLUMN "Frequency of Purchases" TO frequency_of_purchases;


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select purchase_amount , customer_id
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG (purchase_amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
WITH customer_type AS (
    SELECT customer_id,
           previous_purchases,
           CASE
               WHEN previous_purchases = 1 THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer
)
SELECT customer_segment,
       COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


ALTER TABLE customer
ADD COLUMN age_group text;

UPDATE customer
SET age_group = CASE
    WHEN age <= 25 THEN 'Young Adult'
    WHEN age BETWEEN 26 AND 40 THEN 'Adult'
    WHEN age BETWEEN 41 AND 60 THEN 'Middle-aged'
    ELSE 'Senior'
END;

SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;




